version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\CM19Lib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - CM19Lib.Tests/bin/Debug/CM19Lib.Tests.dll
after_test:
  - ps: .\CM19Lib\nuget_pack.ps1
artifacts:
  - path: .\CM19Lib\bin\Debug\CM19Lib.dll
    name: CM19Lib
    type: File
  - path: '*.nupkg'
    name: CM19Lib nupkg
    type: NuGetPackage
deploy:
  - provider: GitHub
    auth_token:
      secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: nFeqkA4BfbPz0Fpqo0Q5+/Y1ISiQ/lGEj3oqH07+XUo9S3FrixM0ENcd2hj3UARu
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

